package:
  name: conda-wrappers
  version: 0.1

source:
  path: ../

build:
  string: 0

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://github.com/conda/conda-build
  license: BSD
