package:
  name: conda-wrappers
  version: "0.1.0"

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - exec-wrappers

about:
  home: https://github.com/gqmelo/exec-wrappers
  license: MIT
  summary: 'Simple package to execute exec-wrappers as a post-link action'
